language: perl6
sudo: false
os:
  - linux
  - osx
perl6:
  - latest
  - '2019.03'
  - '2018.07.1'
install:
  - rakudobrew build zef
  - zef --depsonly install .
  - zef install File::Temp
  - zef build .
