name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        raku-version:
          - 'latest'
          - '2020.05.1'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - if: contains(matrix.os, 'unbuntu')
        run: sudo apt-get install -y libxml2-dev
      - if: contains(matrix.os, 'macOS')
        run: |
            brew update
            brew install libxml2
      - name: Run Tests
        run: prove6 -I. t
      - name: Install Module
        run: zef install --verbose .
