name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        raku-version:
          - 'latest'
          - '2020.05.1'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Linux specific setup
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install -y libxml2-dev
      - name: macOS specific setup
        if: contains(matrix.os, 'macOS')
        run: |
            brew update
            brew install libxml2
      - name: Install Dependencies
        run: |
          zef install --/test LibraryMake
          zef install --deps-only .
          zef build .
          zef install --/test App::Prove6
      - name: Run Tests
        if: ${{ !(contains(matrix.os, 'windows') && !contains(matrix.raku, 'latest')) }}
        run: prove6 -I. t
      - name: Install Module
        if: ${{ !(contains(matrix.os, 'windows') && !contains(matrix.raku, 'latest')) }}
        run: zef install --verbose .
